In [1]:
import numpy as np 

In [2]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [3]:
# creating arrays from lists
height = [1.56, 1.78, 1.91, 1.83, 1.69]
weight = [78, 67, 95, 48, 45]

In [4]:
np_weight = np.array(weight)
np_height = np.array(height)

In [5]:
np_height

array([1.56, 1.78, 1.91, 1.83, 1.69])

In [6]:
# Append two lists
list_2 = height.append(weight)

In [7]:
print(list_2)

None


In [8]:
weight

[78, 67, 95, 48, 45]

In [9]:
height_weight = [[1.56, 1.78, 1.91, 1.83, 1.69],[78, 67, 95, 48, 45]]

In [10]:
height_weight

[[1.56, 1.78, 1.91, 1.83, 1.69], [78, 67, 95, 48, 45]]

In [11]:
np_2D = np.array(height_weight)

In [12]:
np_2D

array([[ 1.56,  1.78,  1.91,  1.83,  1.69],
       [78.  , 67.  , 95.  , 48.  , 45.  ]])

In [15]:
np_2D[1][2]

95.0

In [21]:
np_2D[1, 3]

48.0

In [22]:
np.mean(np_2D[:, 0])

39.78

In [16]:
# regular list of lists
x = [["a", "b"], ["c", "d"]]
[x[0][0], x[1][0]]

# numpy
import numpy as np
np_x = np.array(x)
np_x[:, 0]

array(['a', 'c'], dtype='<U1')

In [17]:
np_x

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')